### ISSUE TITLE
Update while animating/interacting?

### ISSUE THREAD

**Issue by jsvde** [trump-fmi/ol-labels#15]
Any ideas how to fix this?

**Comment by sahinM** [comment]
@jsvde : Do you mean the bug, that the label and so on should update / animate on the view **during** zooming and **not** after it? if yes, I found an [Stackoverflow-article](https://stackoverflow.com/questions/32162725/get-exact-resolution-during-zooming-in-postrender-hook-in-openlayers-3) where someone has a similar problem and get an answer to use **event-listener** on the _map_-object.
They use an event which is **Triggered after a map frame is rendered.** 

The _relevant_ classes which are referenced are:

- [ol.MapEvent](http://openlayers.org/en/v3.8.2/apidoc/ol.MapEvent.html)
- [olx.ViewState](http://openlayers.org/en/latest/apidoc/olx.html#ViewState)
- [olx.FrameState](http://openlayers.org/en/v3.8.2/apidoc/olx.html#FrameState)

Could these help us?

**Comment by jgueth** [comment]
The problem with the suggested solution of the [Stackoverflow-article](https://stackoverflow.com/questions/32162725/get-exact-resolution-during-zooming-in-postrender-hook-in-openlayers-3) is that we don't want to use the map.on function because we prefer an integrated solution where the user doesn't need to add additional code snippets.

**Comment by jgueth** [comment]
Fixed issue with commit #21
